### ISSUE TITLE
service model migrations

### ISSUE THREAD

**Issue by Qard** [feathersjs-ecosystem/feathers-generator#13]
Do you have any particular thoughts on how model updates and migrations would fit into this? Currently when I make a feathers app I manually delete all the model.sync() calls after generating a model and then create a sequelize migration manually. There's not currently a way to programmatically add new fields to a model and create the appropriate migration, so things can sometimes get out of sync. 😞

**Comment by daffl** [comment]
Not specifically. Until Feathers comes with an official model definition format this is the job of the ORM. For Sequelize, there is a guide on Migrations [here](https://docs.feathersjs.com/databases/sequelize.html#migrations) and and example in the [feathers-demos repository](https://github.com/feathersjs/feathers-demos/tree/master/examples/migrations/sequelize). Someone would still need to take on including that as a template in the new generator.

**Comment by slajax** [comment]
@daffl might be worth doing something in the short term kind of like [node-migrate](https://github.com/tj/node-migrate), where you simply implement `up` and `down` methods and maintain state of the migrations. It might make it easier to consolidate once we get further with the model definitions.
