### ISSUE TITLE
answer prompts via args

### ISSUE THREAD

**Issue by slajax** [feathersjs-ecosystem/feathers-generator#64]
overview
---
It would be great if we could answer each of the prompt questions using a `--key value` setup in the cli commands. This will allow us to generate things on the fly so that we do not need to answer every single question, which is useful for things like tests that need to test generated work.

tasks
---
- [ ] come up with naming schema
- [ ] implement some way in feathers-cli to pass through all xargs
- [ ] map xargs to inquirer prompts
- [ ] populate answers using a middleware in generator chain
- [ ] make sure things get generated and still work
- [ ] unblock #16

**Comment by Jaden-Giordano** [comment]
Yeah this would be great! The `--key value` would work great, something for generating an app could look like `feathers generate app --projectName a-simple-project --source feathers --packageManager yarn --api rest --api socketio`.
